name: jewellery
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  lottie: ^2.7.0
  animated_text_kit: ^4.2.2
  get: ^4.6.6
  flutter_svg: ^2.0.9
  animations: ^2.0.8
  firebase_core: ^2.22.0
  firebase_auth: ^4.13.0
  pinput: ^3.0.1
  flutter_firebase_recaptcha: ^1.0.2
  firebase_auth_platform_interface: ^7.0.4
  cloud_firestore: ^4.13.1
  timer_count_down: ^2.2.2
  sms_autofill: ^2.3.0
  animate_do: ^3.1.2
  font_awesome_flutter: ^10.6.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.19.0
  web_socket_channel: ^2.4.0
  http: ^1.1.0
  selection_menu: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo.png
    - assets/icons/logo.png
    - assets/icons/importation.png
    - assets/images/supportIcon.png
    - assets/icons/
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
